### ISSUE TITLE
Need an admin Panel page

### ISSUE THREAD

**Issue by akashgreninja** [akashgreninja/Doggonation#17] opened 2023-05-22 11:00 UTC
Navbar can be different and should look amazing put in sample data 
 Make it look different with animations 
 You can use Tailwind or CSS 
 If you are using CSS do use classes or ID's do not target them by element 
 Create a page in the Pages Folder called AdminPanel 
 go ahead

**Comment by Mansi1236** [comment] 2023-05-22 11:15
Is this issue open? 
If it is then I would like to work on this issue under GSSoC'23
Can you please assign it to me?

**Comment by akashgreninja** [comment] 2023-05-22 11:17
@Mansi1236 I will be assigning you this for now

**Comment by Mansi1236** [comment] 2023-05-22 11:32
Actually I thought the issue is of improving the UI, I don't have much experience in making admin dashboards.
Could you please un-assign it?
Apologies for the inconvenience caused

**Comment by rishuraj1** [comment] 2023-05-22 11:40
@akashgreninja  can you please assign this task to me. also, can you specify about the features of this page. Thank You!

**Comment by akashgreninja** [comment] 2023-05-22 11:41
@Mansi1236 You can work on improving the UI of the Main Home page or the about us Page if you want as well

**Comment by rishuraj1** [comment] 2023-05-22 11:44
@akashgreninja  alright I will try my best. Thank You!

**Comment by akashgreninja** [comment] 2023-05-27 05:13
@rishuraj1 any updates on this?

**Comment by rishuraj1** [comment] 2023-05-27 05:29
@akashgreninja  yes, figuring out some stuffs as my exams are going on till end of this month.  Could you unassign me till then and after my exams are over, if this task still needs to be done, I would definitely like to try. Sorry for the inconvenience.

**Comment by vk20july** [comment] 2023-06-09 08:31
can i try this @EffDuBois sir

**Comment by oshinsaraf** [comment] 2023-06-11 11:15
Can you assign this to me under GSSOC'23?

**Closed** 2023-06-12 12:34 UTC
Labels: gssoc23
